---
- hosts: rtr1
  roles:
    - role : network-engine

  tasks:
    - name: get openconfig from device
      netconf_get:
         source: running
         filter: <interfaces xmlns="http://openconfig.net/yang/interfaces"></interfaces>
         display: json
      register: result
      tags: netconf_get

    - name: write results to config file
      copy: content="{{ result["output"]["rpc-reply"]["data"] }}" dest=templates/device_config.json

    - name: read json oupput to facts using network-engine
      debug:
        msg: "{{ lookup('template', 'templates/device_config.json') }}"
      register: result
      tags: json_t

    - set_fact: interface_list = "{{ result["msg"]["interfaces"]["interface"] }}"
      register: interface_list

    - name: Print list of interfaces
      debug: 
         msg: "{{ item }}" 
      with_items:
          - " {{ interface_list }}"

