---
- hosts: rtr1
  roles:
    - role : network-engine

  tasks:
    - name: get openconfig from device
      net_openconfig:
         schema:
            - openconfig-interfaces
         data:
            interfaces:
                interface:
                - name : 'GigabitEthernet 0/0/0/0'
                  enabled : True
        operation: merge
      register: result
      tags: config

