---
- hosts: rtr1
  roles:
    - role : network-engine

  tasks:
    - name: get openconfig from device
      netconf_get:
         source: running
         filter: <interfaces xmlns="http://openconfig.net/yang/interfaces"></interfaces>
         display: json
      register: result
      tags: netconf_get

    - name: write results to config file
      copy: content="{{ result["output"]["rpc-reply"]["data"] }}" dest=templates/device_config.json

    - name: read json oupput to facts using network-engine
      debug:
        msg: "{{ lookup('template', 'templates/device_config.json') }}"
      register: result
      tags: json_t

    - set_fact: interface_list = "{{ result["msg"]["interfaces"]["interface"] }}"
      register: interface_list

    - name: Print list of interfaces
      debug: 
         msg: "{{ item }}" 
      with_items:
          - " {{ interface_list }}"

    - name:  Parse interface config in openconfig data model and write into xml for netconf
      openconfig_parser:
          src: 'interface_openconfig.json'
          ns_map: 'openconfig_ns_map.yml'
          output: 'templates/interface_openconfig.xml'
      register: result

    - name: Play config via netconf to IosXr who understands openconfig model
      netconf_config:
          src: 'interface_openconfig.xml'
      register: result
      tags: iosxr_play

    - assert: &true
        that:
          - 'result.changed == true'

- hosts: vsrx01
  tasks:
    - name : Parse interface openconfig and convert to junos native xml
      openconfig_parser:
          src: 'interface_openconfig.json'
          output: 'templates/junos_interface_openconfig.xml'
          xpath_map: 'junos_open_to_native_xpath_map.yml'
      tags: parser

    - name: Play interface config via netconf to Junos in Junos native xml
      netconf_config:
          src: 'junos_interface_openconfig.xml'
      register: result
      tags: junos_play

    - assert:
        that:
          - 'result.changed == true'

